# application.properties

# application.properties ? CORRETO
spring.profiles.active=${APP_PROFILE:dev}
# SPRING_PROFILES_ACTIVE=prod

# Configura��o de logs gen�ricos
logging.level.root=INFO
logging.level.org.springframework.security=INFO

# Desativa open-in-view por padr�o
spring.jpa.open-in-view=false

# Local padr�o das migra��es
spring.flyway.locations=classpath:db/migration

# Formata��o SQL padr�o (�til no dev, mas desligado no prod via override)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# CORS liberado para front-end local
cors.origins=http://localhost:4200,http://localhost:5173,http://localhost:3000

# Porta padr�o (pode ser sobrescrita nos perfis)

server.port=7070